run:
  tests: false

  skip-dirs:
    - bin

linters-settings:
  revive:
  staticcheck:
  stylecheck:
  gocyclo:
  gosimple:
  gocritic:
  staticcheck:
  gosec:

linters:
  enable:
    - revive
    - staticcheck
    - stylecheck
    - gocyclo
    - gosimple
    - gocritic
    - staticcheck
    - gosec