version: '3.9'

services: 
    postgres:
        restart: always
        image: postgres:latest
        hostname: postgres
        container_name: avito_adv_postgres
        env_file: .env
        ports: 
            - 5432
    web:
        restart: always
        container_name: avito_adv_web
        build: 
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - .:/code
        command: > 
            bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; 
            go build -o ./bin/main cmd/advertising_avito/main.go 
            && ./bin/main"
        ports: 
            - 8000:8000
        depends_on: 
            - postgres
        links:
            - postgres
